export const mockNetworkStatus = {
  data: {
    version: '4.0.0-beta.1.1122f52',
    networkVersion: '1.0',
    chainID: '02000000',
    lastBlockID: '1ed7b2eb634075283baf4be92a4f0808ecd84c898c1bd6fdb59cbb700dd3eaed',
    height: 60361,
    finalizedHeight: 60360,
    syncing: false,
    unconfirmedTransactions: 0,
    genesis: {
      block: {
        fromFile: './config/genesis_block.blob',
      },
      blockTime: 10,
      bftBatchSize: 103,
      maxTransactionsSize: 15360,
      minimumCertifyHeight: 10611,
      chainID: '02000000',
    },
    genesisHeight: 0,
    registeredModules: [
      'auth',
      'dynamicReward',
      'fee',
      'interoperability',
      'legacy',
      'pos',
      'random',
      'token',
      'validators',
    ],
    moduleCommands: [
      'auth:registerMultisignature',
      'interoperability:submitMainchainCrossChainUpdate',
      'interoperability:initializeMessageRecovery',
      'interoperability:recoverMessage',
      'interoperability:registerSidechain',
      'interoperability:recoverState',
      'interoperability:terminateSidechainForLiveness',
      'legacy:reclaimLSK',
      'legacy:registerKeys',
      'pos:registerValidator',
      'pos:reportMisbehavior',
      'pos:unlock',
      'pos:updateGeneratorKey',
      'pos:stake',
      'pos:changeCommission',
      'pos:claimRewards',
      'token:transfer',
      'token:transferCrossChain',
    ],
    network: {
      version: '1.0',
      port: 7667,
      seedPeers: [
        {
          ip: 'betanet-seed-01.lisk.com',
          port: 7667,
        },
        {
          ip: 'betanet-seed-02.lisk-nodes.net',
          port: 7667,
        },
        {
          ip: 'betanet-seed-03.lisk.com',
          port: 7667,
        },
        {
          ip: 'betanet-seed-04.lisk-nodes.net',
          port: 7667,
        },
        {
          ip: 'betanet-seed-05.lisk.com',
          port: 7667,
        },
      ],
    },
  },
  meta: {
    lastUpdate: 1684923803,
    lastBlockHeight: 60361,
    lastBlockID: '1ed7b2eb634075283baf4be92a4f0808ecd84c898c1bd6fdb59cbb700dd3eaed',
  },
};
