export const GET_TRANSACTIONS_QUERY = 'GET_TRANSACTIONS';
export const GET_APPLICATIONS_QUERY = 'GET_APPLICATIONS_QUERY';
export const GET_APPLICATION_QUERY = 'GET_APPLICATION_QUERY';
export const GET_TRANSACTION_QUERY = 'GET_TRANSACTION';
export const APPLICATION = 'APPLICATION';
export const GET_APPLICATION_STATS = 'GET_APPLICATION_STATS';
export const GET_PRIORITY_FEES = 'GET_PRIORITY_FEES';
export const GET_NETWORK_STATUS = 'GET_NETWORK_STATUS';
