require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Lisk' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'LiskTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'Lisk-tvOS' do
  # Pods for Lisk-tvOS

  target 'Lisk-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
