fastlane_version '2.113.0'

before_all do
  # ensure_git_branch
  # ensure_git_status_clean
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :fetch_certificates do
    match(app_identifier: 'io.lisk.mobile', type: 'development')
    match(app_identifier: 'io.lisk.mobile', type: 'appstore')
  end

  desc 'Build the app'
  lane :build do
    fetch_certificates
    increment_build_number(xcodeproj: './ios/Lisk.xcodeproj')
    gym(scheme: 'Lisk', project: './ios/Lisk.xcodeproj')
  end

  desc 'Build the app and ship to Testflight'
  lane :beta do
    build
    pilot
  end
end

platform :android do
end
